display/urls.py
from django.urls import path

from . import views

app_name = "display"
urlpatterns = [
    #Main Views
    path('', views.Main.as_view(), name="main"),
    path('members/', views.MemberView.as_view(), name="members"),

    #Event CRUD Views
    path('event/create', views.EventCreate.as_view(), name="event_create"),
    path('event/<int:pk>/update', views.EventUpdate.as_view(), name="event_update"),
    path('event/<int:pk>/delete', views.EventDelete.as_view(), name="event_delete"),
    
    #Practice CRUD Views
    path('practice/create', views.PracticeCreate.as_view(), name="practice_create"),
    path('practice/<int:pk>/update', views.PracticeUpdate.as_view(), name="practice_update"),
    path('practice/<int:pk>/delete', views.PracticeDelete.as_view(), name="practice_delete"),

    #Band CRUD Views
    path('event/<int:pk>/band/create', views.BandCreate.as_view(), name="band_create"), #Event_id for foreign key creation
    path('band/<int:pk>/update', views.BandUpdate.as_view(), name="band_update"),
    path('band/<int:pk>/delete', views.BandDelete.as_view(), name="band_delete"),

    #BandMember CRUD Views
    path('band/<int:pk>/member/create', views.BandMemberCreate.as_view(), name="bandmember_create"), #Band_id for foreign key creation
    path('member/delete/<int:band_id>/<int:member_id>', views.BandMemberDelete.as_view(), name="bandmember_delete"),

]

home/urls.py
from django.urls import path

from . import views

app_name = "home" #Redirects to landing page if url 'home:home'
urlpatterns = [
    path('', views.Home.as_view(), name="home"),
]

settings/urls.py
from django.urls import path
from .views import ProfileView, AdminView

app_name = "settings"
urlpatterns = [
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('admin/', AdminView.as_view(), name="admin"),
]

super/urls.py
from django.urls import path
from .views import SuperView, BandDetailView

app_name = "super"
urlpatterns = [
    path('', SuperView.as_view(), name="home"),
    path('detail/<int:pk>', BandDetailView.as_view(), name="detail"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('display/', include("display.urls")),
    path('settings/', include("settings.urls")),
    path('super/', include("super.urls")),

]

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
import json
from datetime import datetime as dt

from display.models import Event, Practice

# Create your views here.

#Landing Page View (URL: '')
class Home(TemplateView):
    def get(self, request):
        events = []
        for event in Event.objects.all():
            if dt.combine(event.date,event.time)>dt.now():
                events.append(event)
        practices = Practice.objects.all()
        ctx = {
            "description":"Universe also known as Hall 1 Jam Band's Webpage",
            "keywords":"Universe, Hall 1, Jam Band, Hall 1 Jam Band, NTU, Nanyang Technological University,"+
            "NTU Jam Band, Oners, Universe Jam Band",
            "event_list":events, #Ref Event & Practice Models to show all values in landing page
        }
        if events or practices:
            events_json = []
            for event in events:
                events_json.append({
                    'title':event.name,
                    'start':event.date.strftime("%Y-%m-%d"),
                    'end':event.date.strftime("%Y-%m-%d")
                })
            for practice in practices:
                events_json.append({
                    'title':practice.band.name,
                    'start':practice.date.strftime("%Y-%m-%dT")+practice.startTime.strftime("%H:%M"),
                    'end':practice.date.strftime("%Y-%m-%dT")+practice.endTime.strftime("%H:%M")
                })
            ctx["events_json"] = json.dumps(events_json)
        else:
            ctx["events_json"] = json.dumps({})
        return render(request=request, template_name='home/landing.html', context=ctx)
    

home/templates/TEMPLATE.html
{% extends "base_bootstrap.html" %}

{% block head %} {% endblock %}

{% block navbar %} {% endblock %}

{% block welcome %} {% endblock %}

{% block content %}



{% endblock %}

{% block footer %} {% endblock %}

home/templates/base_bootstrap.html
<!DOCTYPE html>
<!--
    THIS IS THE BASE TEMPLATE FOR ALL HTML TEMPLATES IN THIS APPLICATION
-->
{% load static %}
<html lang="en">
    <head>
        <title>Universe</title>
        <meta charset="utf-8"><!-- html5 version of http-equiv="Content-Type"... -->
        <meta name="description" content="{{description}}">
        <meta name="keywords" content="{{keywords}}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="author" href="https://github.com/TZBAvyy" />
        <link rel="canonical" href="https://universejamband.pythonanywhere.com{% block canonical_url %}{% endblock %}" />

        <script {% comment %} FullCalender6.1.13 {% endcomment %}
            src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.13/index.global.min.js" 
            integrity="sha384-0CB6A5Ktedhcwwd+5zVXQcYCIMCdJZQ3l7xbJF1RNPVsRb6GHDlLdfNdMMQyLHvE" 
            crossorigin="anonymous"></script>

        <script {% comment %} FullCalender6.1.10 Bootstrap5 Theme {% endcomment %}
            src="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap5@6.1.10/index.global.min.js" 
            integrity="sha384-Bw7vQnyU2pxq8Pka85jZvv7NKuSk8ISPllbhcF+Fs30AsZnris19tQU/01szKjvA" 
            crossorigin="anonymous"></script>

        <link {% comment %} Bootstrap5.3.3 {% endcomment %}
            rel="stylesheet" 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
            crossorigin="anonymous">
        
        <script {% comment %} Bootstrap5.3.3 Bundle {% endcomment %}
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
            crossorigin="anonymous"></script>

        <link {% comment %} Bootstrap-icons1.8.1 {% endcomment %}
            rel="stylesheet" 
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" 
            integrity="sha384-He3RckdFB2wffiHOcESa3sf4Ida+ni/fw9SSzAcfY2EPnU1zkK/sLUzw2C5Tyuhj" 
            crossorigin="anonymous">

        <link 
            rel="stylesheet" 
            href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
            integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
            crossorigin="anonymous">

        <link 
            rel="stylesheet" 
            href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css" 
            integrity="sha384-knhdgIEP1JBPHETtXGyUk1FXV22kd1ZAN8yyExweAKAfztV5+kSBjUff4pHDG38c" 
            crossorigin="anonymous">

        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" >

        <!-- Used for mobile resizing -->
        <style> 
            @media (max-width: 767.98px) {
                .fc .fc-toolbar.fc-header-toolbar {
                    display: block;
                    text-align: center;
                }
            
                .fc-header-toolbar .fc-toolbar-chunk {
                    display: block;
                }
            }
        </style>

        {% block head %} {% endblock %}

    </head>
    <body class="pt-5">
        <div class="container pt-3">
        {% block navbar %} {% endblock %}
        {% block welcome %} {% endblock %}
        {% block messages %}
            {% if messages %}
            {% for msg in messages %}
                <div class="alert alert-{{msg.level_tag}}" role="alert">
                {{msg.message}}
                </div>
            {% endfor %}
            {% endif %}
        {% endblock %}
        {% block content %}
        {% endblock %}
        </div>
        {% block footer %} {% endblock %}
    </body>
</html>

home/templates/nav.html
<!-- NAVBAR TEMPLATE FOR ALL NON-FORM HTML TEMPLATES -->
{% load static %}
{% block navbar %} 
<div class="container-fluid">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <div class="navbar-brand text-dark">
                <img alt="" src="{% static 'images/logo.png' %}" width="30" height="35" class="pb-1">
                Universe
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse w-100" id="navbarToggle">
                <div class="navbar-brand text-dark w-100"></div>

                <ul class="navbar-nav w-100">
                    <li class="nav-item">
                        <a class="nav-link text-primary" href="{% url 'home:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-primary" href="{% url 'display:main' %}">Schedule Practice</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-primary" href="{% url 'display:members' %}">Member List</a>
                    </li>
                </ul>

                <ul class="navbar-nav w-100 justify-content-end">

                    {% if user.is_authenticated %}

                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.first_name }}
                            </a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    {% if user.is_superuser %}
                                        <a class="dropdown-item text-primary" href="{% url 'super:home' %}">Admin</a>
                                    {% endif %}
                                </li>

                                <li>
                                    <a class="dropdown-item text-primary" href="{% url 'settings:profile' user.id %}">Settings</a>
                                </li>
                            </ul>
                            
                        </li>
                        
                        <li class="nav-item">
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link nav-link text-dark btn-outline-primary px-2">Logout</button>
                            </form>
                        </li>

                    {% else %}
                    <li class="nav-item">
                        <a style="text-decoration: none;" class="btn btn-link text-dark btn-outline-primary px-2" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
{% endblock %}