display/urls.py
from django.urls import path

from . import views

app_name = "display"
urlpatterns = [
    #Main Views
    path('', views.Main.as_view(), name="main"),
    path('members/', views.MemberView.as_view(), name="members"),

    #Event CRUD Views
    path('event/create', views.EventCreate.as_view(), name="event_create"),
    path('event/<int:pk>/update', views.EventUpdate.as_view(), name="event_update"),
    path('event/<int:pk>/delete', views.EventDelete.as_view(), name="event_delete"),
    
    #Practice CRUD Views
    path('practice/create', views.PracticeCreate.as_view(), name="practice_create"),
    path('practice/<int:pk>/update', views.PracticeUpdate.as_view(), name="practice_update"),
    path('practice/<int:pk>/delete', views.PracticeDelete.as_view(), name="practice_delete"),

    #Band CRUD Views
    path('event/<int:pk>/band/create', views.BandCreate.as_view(), name="band_create"), #Event_id for foreign key creation
    path('band/<int:pk>/update', views.BandUpdate.as_view(), name="band_update"),
    path('band/<int:pk>/delete', views.BandDelete.as_view(), name="band_delete"),

    #BandMember CRUD Views
    path('band/<int:pk>/member/create', views.BandMemberCreate.as_view(), name="bandmember_create"), #Band_id for foreign key creation
    path('member/delete/<int:band_id>/<int:member_id>', views.BandMemberDelete.as_view(), name="bandmember_delete"),

]

home/urls.py
from django.urls import path

from . import views

app_name = "home" #Redirects to landing page if url 'home:home'
urlpatterns = [
    path('', views.Home.as_view(), name="home"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('display/', include("display.urls")),
    path('settings/', include("settings.urls")),
    path('super/', include("super.urls")),

]

display/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# ALL MODELS FOLLOW THIS ERD: https://drawsql.app/teams/solo-196/diagrams/jamband

class Section(models.Model):
    instrument = models.CharField(
            max_length=50, 
            help_text='Enter a section (e.g. Bass)',
            validators=[MinLengthValidator(2, "Section instrument must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Sections object."""
        return self.instrument
    
class Member(models.Model):
    name = models.CharField(
            max_length=50, 
            help_text='Enter a member\'s full name (e.g. Avi)',
            validators=[MinLengthValidator(2, "Member name must be greater than 1 character")]
    )
    sections = models.ManyToManyField('Section',through='MemberSection', related_name='players')

    def __str__(self):
        """String for representing the Members object."""
        return self.name
    
class MemberSection(models.Model):
    class Proficiency(models.IntegerChoices):
        LEARNING = 1
        CAN_PLAY = 2
    
    proficiency = models.IntegerField(choices=Proficiency)

    section = models.ForeignKey('Section', on_delete=models.CASCADE, null=False)
    member = models.ForeignKey('Member', on_delete=models.CASCADE, null=False)

    def __str__(self):
        """String for representing the MemberSections object."""
        if self.proficiency==1:
            s = " (L)"
        else:
            s = ""
        return f"{self.member} ({self.section}{s})"

class Event(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Event name must be greater than 1 character")]
    )
    date = models.DateField()
    
    time = models.TimeField()

    class Meta:
        ordering = ['-date','-time']

    # Shows up in the admin list
    def __str__(self):
        """String for representing the Events object."""
        return self.name
    
class Band(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Event name must be greater than 1 character")]
    )
    event = models.ForeignKey('Event', models.CASCADE, null=False, related_name='bands')
    members = models.ManyToManyField('Member', through='BandMember', related_name='bands')

    # Shows up in the admin list
    def __str__(self):
        """String for representing the Bands object."""
        return self.name
    
class BandMember(models.Model):
    band = models.ForeignKey('Band', models.CASCADE, null=False)
    member = models.ForeignKey('Member', models.CASCADE, null=False)

    def __str__(self):
        """String for representing the BandMembers object."""
        return f"{self.member} IN {self.band}"
    
class Practice(models.Model):
    band = models.ForeignKey('Band', models.CASCADE, null=False)

    date = models.DateField()

    startTime = models.TimeField()

    endTime = models.TimeField()
    
    class Meta:
        ordering = ['date','startTime']

    def __str__(self):
        """String for representing the Practices object."""
        return f"[{self.date}] {self.band} from {self.startTime} to {self.endTime}"
    

display/forms.py
from django import forms
from django.db.models import Q
from .models import Event, Practice, Band, BandMember, Member
from datetime import datetime, time

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        widgets = {
            "date": forms.DateInput(attrs={'type':'date'}),
            "time": forms.TimeInput(attrs={'type': 'time'})
        }  
    
class BandMemberForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        pk = kwargs.pop('band_pk')
        super().__init__(*args, **kwargs)
        self.fields['member'].queryset = Member.objects.filter(~Q(bands__id=pk))

    class Meta:
        model = BandMember
        fields = ['member']

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = ['name','members']
        widgets = {'members':forms.CheckboxSelectMultiple}

class PracticeForm(forms.ModelForm):
    band = forms.ModelChoiceField(queryset=Band.objects.filter(event__date__gt=datetime.now().date()))
    class Meta:
        model = Practice
        fields = '__all__'
        widgets = {
            "date": forms.DateInput(attrs={'type':'date'}),
            "startTime": forms.TimeInput(attrs={'type': 'time'}),
            "endTime": forms.TimeInput(attrs={'type': 'time'})
        }  
    
    def clean(self): #Overrided clean method for additional validation
        cleaned_data = super(PracticeForm, self).clean()
        start = cleaned_data.get('startTime')
        end = cleaned_data.get('endTime')

        if end==time(0,0):
            pass
        elif start > end: #start and end time validation
            raise forms.ValidationError("Start time cannot be later than end time!")
        
        date = cleaned_data.get('date')

        #Checks for if the current datetime > date + startTime to prevent booking of the room in the past
        dateNow = datetime.now().date()
        time8am = time(8,0)
        
        if dateNow>date:
            raise forms.ValidationError("Error, cannot book a practice in the past")
        
        if time8am>start:
            raise forms.ValidationError("Error, cannot book a practice before 8am")

        conflicts = Practice.objects.filter(
                date=date,
                startTime__lt=end, #filter for any practices with startTime < endTime of this practice
                endTime__gt=start, #filter for any practices with endTime > startTime of this practice
            ).exclude(
                id=self.instance.id
            )
        if any(conflicts): #conflict validation 
            st = "Room is booked from "
            for i in conflicts:
                st += f"{i.startTime} to {i.endTime}, "
            raise forms.ValidationError(f"Conflict! {st}")
        return cleaned_data
    
class UpdatePracForm(forms.ModelForm):
    class Meta:
        model = Practice
        fields = '__all__'
        widgets = {
            "date": forms.DateInput(attrs={'type':'date'}),
            "startTime": forms.TimeInput(attrs={'type': 'time'}),
            "endTime": forms.TimeInput(attrs={'type': 'time'}),
            "band": forms.HiddenInput(),
        }  
    
    def clean(self): #Overrided clean method for additional validation
        cleaned_data = super(UpdatePracForm, self).clean()
        start = cleaned_data.get('startTime')
        end = cleaned_data.get('endTime')

        if end==time(0,0):
            pass
        elif start > end: #start and end time validation
            raise forms.ValidationError("Start time cannot be later than end time!")
        
        date = cleaned_data.get('date')

        #Checks for if the current datetime > date + startTime to prevent booking of the room in the past
        dateNow = datetime.now().date()
        time8am = time(8,0)
        
        if dateNow>date:
            raise forms.ValidationError("Error, cannot book a practice in the past")
        
        if time8am>start:
            raise forms.ValidationError("Error, cannot book a practice before 8am")

        conflicts = Practice.objects.filter(
                date=date,
                startTime__lt=end, #filter for any practices with startTime < endTime of this practice
                endTime__gt=start, #filter for any practices with endTime > startTime of this practice
            ).exclude(
                id=self.instance.id
            )
        if any(conflicts): #conflict validation 
            st = "Room is booked from "
            for i in conflicts:
                st += f"{i.startTime} to {i.endTime}, "
            raise forms.ValidationError(f"Conflict! {st}")
        return cleaned_data

display/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.views import View
from typing import Any
import json

from .models import *
from .forms import *
# Create your views here.

def createPracJson():
    practices = Practice.objects.all()
    if practices:
        practices_json = []
        for practice in practices:
            practices_json.append({
                'title':practice.band.name,
                'url': reverse('display:practice_update',args=[practice.id]),
                'start':practice.date.strftime("%Y-%m-%dT")+practice.startTime.strftime("%H:%M"),
                'end':practice.date.strftime("%Y-%m-%dT")+practice.endTime.strftime("%H:%M")
            })
        practices_json = json.dumps(practices_json)
    else:
        practices_json = json.dumps({})
    return practices_json

class Main(View):
    ctx = {
        "description":"Universe also known as Hall 1 Jam Band's Webpage",
        "keywords":"Universe, Hall 1, Jam Band, Hall 1 Jam Band, NTU, Nanyang Technological University",
    }

    def get(self, request):
        self.ctx["practice_list"] = Practice.objects.all()
        self.ctx["event_list"] = Event.objects.all()
        self.ctx["band_list"] = Band.objects.all()
        self.ctx["bandmember_list"] = BandMember.objects.all()
        self.ctx["practices_json"] = createPracJson()
        return render(request=request, template_name="display/main.html", context=self.ctx)
    
class MemberView(LoginRequiredMixin, View):
    ctx = {
        "description":"",
        "keywords":"",
    }

    def get(self, request):
        self.ctx["section_list"] = Section.objects.all()
        self.ctx["membersection_list"] = MemberSection.objects.all().order_by('-proficiency')
        return render(request=request, template_name="display/members.html", context=self.ctx)

#Practice Model Views
class PracticeCreate(LoginRequiredMixin, CreateView):
    model = Practice
    form_class = PracticeForm
    template_name = "display/form.html"
    success_url = reverse_lazy('display:main')

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["practices_json"] = createPracJson()
        return context

class PracticeUpdate(LoginRequiredMixin, UpdateView):
    model = Practice
    form_class = UpdatePracForm
    template_name = "display/form.html"
    success_url = reverse_lazy('display:main')
    
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["practices_json"] = createPracJson()
        return context

class PracticeDelete(LoginRequiredMixin, DeleteView):
    model = Practice
    fields = '__all__'
    template_name = "display/confirm_delete.html"
    success_url = reverse_lazy('display:main')

#THESE VIEWS ARE FOR SUPERUSER APP
#Event Model Views
class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm
    template_name = "super/form.html"
    success_url = reverse_lazy('super:home')

class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name = "super/form.html"
    success_url = reverse_lazy('super:home')

class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    fields = '__all__'
    template_name = "super/confirm_delete.html"
    success_url = reverse_lazy('super:home')

#Band Model Views & Forms
class BandCreate(LoginRequiredMixin, CreateView):
    model = Band
    form_class = BandForm
    template_name = "super/form.html"
    success_url = reverse_lazy('super:home')

    def form_valid(self, form: forms.BaseModelForm) -> HttpResponse:
        form.instance.event = get_object_or_404(Event, pk=self.kwargs['pk'])
        return super().form_valid(form)
    
class BandUpdate(LoginRequiredMixin, UpdateView):
    model = Band
    fields = ['name']
    template_name = "super/form.html"
    success_url = reverse_lazy('super:home')

class BandDelete(LoginRequiredMixin, DeleteView):
    model = Band
    fields = ['name']
    template_name = "super/confirm_delete.html"
    success_url = reverse_lazy('super:home')

#Band Model Views
class BandMemberCreate(LoginRequiredMixin, CreateView):
    model = BandMember
    template_name = "super/form.html"
    form_class = BandMemberForm
    success_url = reverse_lazy('super:home')

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super(BandMemberCreate, self).get_form_kwargs()
        kwargs['band_pk'] = self.kwargs['pk']
        return kwargs

    def form_valid(self, form: forms.BaseModelForm) -> HttpResponse:
        form.instance.band = get_object_or_404(Band, pk=self.kwargs['pk'])
        return super().form_valid(form)

class BandMemberDelete(LoginRequiredMixin, DeleteView):
    model = BandMember
    template_name = "super/confirm_delete.html"
    success_url = reverse_lazy('super:home')

    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        if queryset is None:
            queryset = self.get_queryset()
        band = self.kwargs["band_id"]
        member = self.kwargs["member_id"]
        obj = BandMember.objects.filter(band=band,member=member)
        return obj

display/templates/display/band_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Band</h1>

<p>Are you sure you want to delete the band: {{ band }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

display/templates/display/band_form.html
{% extends "base_bootstrap.html" %}

{% block welcome %} 
    <h1>Band Form</h1>
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'display:main' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

display/templates/display/confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center">

<div>
  <h1>Deletion!</h1>
</div>

<div>
  <p>Are you sure you want to delete this practice?</p>
</div>

<div>
  <form action="" method="POST" >
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'display:main' %}' ; return false;" value="Cancel">
  </form>
</div>

</div>
{% endblock %}

display/templates/display/form.html
{% extends "base_bootstrap.html" %}

{% block head %} 
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                eventClick: function(info) {
                    var eventObj = info.event;
                    window.open(eventObj.url,_self);
                },
                contentHeight:"auto",
                themeSystem: 'bootstrap5',
                initialView: 'timeGridWeek',
                scrollTime: '12:00:00',
                slotMinTime: '08:00:00',
                headerToolbar: {
                    left: 'prev,next',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek'
                },
                buttonText: {
                    dayGridMonth: "Month",
                    timeGridWeek: "Week"
                },
                footerToolbar: {
                    left:'',
                    center:'scrollTop',
                    right:''
                },
                customButtons: {
                    scrollTop: {
                        text: 'Back to top',
                        click: function() {
                            window.scrollTo(0, 0);
                        }
                    }
                },
                events: {{ practices_json|safe }}
            });
            
            calendar.render();
        });
    </script>
{% endblock %}

{% block navbar %}
    {% include "nav.html" %}
{% endblock %}

{% block welcome %} 
    {% if object %}
        <h2>Update Practice for {{ object.band }}</h2>
        <h4>Previous: {{ object.date|date:'l, d/m/Y' }} from {{object.startTime|date:'h:i:s'}} to {{object.endTime|date:'h:i:s'}}</h4>
    {% else %}
        <h2>Schedule Practice</h2>
    {% endif %}
{% endblock %}

{% block content %}
<div class="row">
    <form action="" method="post">
        {% load crispy_forms_tags %}
        {% csrf_token %}
        {{ form|crispy }}
        {{ form.band.as_hidden }}
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'display:main' %}' ; return false;" value="Cancel">
    </form>
</div>

<div class="row my-3">
    <div class="col-lg">
        <div id="calendar"></div>
    </div>
</div>
{% endblock %}

display/templates/display/main.html
<!-- Main Template for Display App -->
{% extends "base_bootstrap.html" %}

{% block head %} 
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                eventClick: function(info) {
                    var eventObj = info.event;
                    window.open(eventObj.url,_self);
                },
                contentHeight:"auto",
                themeSystem: 'bootstrap5',
                initialView: 'timeGridWeek',
                scrollTime: '12:00:00',
                slotMinTime: '08:00:00',
                headerToolbar: {
                    left: 'prev,next',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek'
                },
                buttonText: {
                    dayGridMonth: "Month",
                    timeGridWeek: "Week"
                },
                footerToolbar: {
                    left:'',
                    center:'scrollTop',
                    right:''
                },
                customButtons: {
                    scrollTop: {
                        text: 'Back to top',
                        click: function() {
                            window.scrollTo(0, 0);
                        }
                    }
                },
                events: {{ practices_json|safe }}
            });
            
            calendar.render();
        });
    </script>
{% endblock %}

{% block canonical_url %}{% url 'display:main' %}{% endblock %}

{% block navbar %} 
    {% include "nav.html" %}
{% endblock %}

{% block welcome %} 
    <h1>Practice Scheduler App</h1>
{% endblock %}

{% block content %} 

<div class="row">
    <a href="{% url 'display:practice_create' %}" class="btn btn-primary" role="button">Schedule new practice</a>
    {% if practice_list %}
    <table class="table table-hover table-bordered border-primary table-sm caption-top">
        <caption>
            <a href="#calendar" class="btn btn-primary" role="button" onclick="">Scroll to Schedule</a>
        </caption>

        <thead>
            <tr class="table-dark">
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Band</th>
                <th scope="col">Edit</th>
            </tr>
        </thead>
        <tbody>
            {% for practice in practice_list %}
            <tr class="">
                <td>{{ practice.date }}</td>
                <td>{{ practice.startTime|date:'f a' }}-{{ practice.endTime|date:'f a' }}</td>
                <td>{{ practice.band }}</td>
                <td>
                    <a href="{% url 'display:practice_update' practice.id %}" class="btn btn-success" role="button">Update</a>
                    <a href="{% url 'display:practice_delete' practice.id %}" class="btn btn-danger" role="button">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>There are no practices scheduled.</p>
    {% endif %}
</div>

<div class="row mb-3">
    <div class="col-lg">
        <h3>Schedule for Practices</h3>
        <div id="calendar"></div>
    </div>
</div>

{% endblock %}

{% block footer %} {% endblock %}

display/templates/display/members.html
{% extends "base_bootstrap.html" %}

{% block canonical_url %}{% url 'display:members' %}{% endblock %}

{% block navbar %} 
    {% include "nav.html" %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <h3>Band Members</h3>
        {% if membersection_list %}
            {% for section in section_list%}
                <div class="col-md-2">
                <h4>{{ section }}</h4>
                <ol>
                    {% for member in membersection_list %}
                    {% if member.section == section %}
                        <li>
                            {{ member.member }}
                            {% if member.proficiency == 1 %}
                            <b>(L)</b>
                            {% endif %}
                        </li>
                    {% endif %}
                    {% endfor %}
                </ol>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}