display/urls.py
from django.urls import path

from . import views

app_name = "display"
urlpatterns = [
    #Main Views
    path('', views.Main.as_view(), name="main"),
    path('members/', views.MemberView.as_view(), name="members"),

    #Event CRUD Views
    path('event/create', views.EventCreate.as_view(), name="event_create"),
    path('event/<int:pk>/update', views.EventUpdate.as_view(), name="event_update"),
    path('event/<int:pk>/delete', views.EventDelete.as_view(), name="event_delete"),
    
    #Practice CRUD Views
    path('practice/create', views.PracticeCreate.as_view(), name="practice_create"),
    path('practice/<int:pk>/update', views.PracticeUpdate.as_view(), name="practice_update"),
    path('practice/<int:pk>/delete', views.PracticeDelete.as_view(), name="practice_delete"),

    #Band CRUD Views
    path('event/<int:pk>/band/create', views.BandCreate.as_view(), name="band_create"), #Event_id for foreign key creation
    path('band/<int:pk>/update', views.BandUpdate.as_view(), name="band_update"),
    path('band/<int:pk>/delete', views.BandDelete.as_view(), name="band_delete"),

    #BandMember CRUD Views
    path('band/<int:pk>/member/create', views.BandMemberCreate.as_view(), name="bandmember_create"), #Band_id for foreign key creation
    path('member/delete/<int:band_id>/<int:member_id>', views.BandMemberDelete.as_view(), name="bandmember_delete"),

]

home/urls.py
from django.urls import path

from . import views

app_name = "home" #Redirects to landing page if url 'home:home'
urlpatterns = [
    path('', views.Home.as_view(), name="home"),
]

settings/urls.py
from django.urls import path
from .views import ProfileView, AdminView

app_name = "settings"
urlpatterns = [
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('admin/', AdminView.as_view(), name="admin"),
]

super/urls.py
from django.urls import path
from .views import SuperView, BandDetailView

app_name = "super"
urlpatterns = [
    path('', SuperView.as_view(), name="home"),
    path('detail/<int:pk>', BandDetailView.as_view(), name="detail"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('display/', include("display.urls")),
    path('settings/', include("settings.urls")),
    path('super/', include("super.urls")),

]

super/models.py
from django.db import models

# Create your models here.

super/views.py
from typing import Any
from datetime import datetime as dt
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from display.models import Event, Band, MemberSection
# Create your views here.

class SuperView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Event
    template_name = "super/super.html"

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["dateNow"] = dt.now().date()
        return context

class BandDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Band
    template_name = "super/band_detail.html"

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["membersection_list"] = MemberSection.objects.all()
        return context

super/templates/super/band_detail.html
{% extends "base_bootstrap.html" %}

{% block head %} {% endblock %}

{% block navbar %}{% include "nav.html" %}{% endblock %}

{% block welcome %} {% endblock %}

{% block content %}

<a class="btn btn-secondary" href="{% url 'super:home' %}">Back</a>

<a class="btn btn-primary" href="{% url 'settings:admin' %}">Members' Event Contribution Page</a>

<a class="btn btn-danger" href="{% url 'display:band_delete' object.id %}">Delete Band</a>

<h2>{{ object }}</h2>

{% if object %}
    <table class="table table-hover table-sm caption-top">
        <caption><a class="btn btn-success" href="{% url 'display:bandmember_create' object.id %}">Add Band Member</a></caption>
        <thead>
        <tr class="table-dark">
            <th scope="col">#</th>
            <th scope="col">Band Members</th>
            <th scope="col">Sections</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% if object.members.all %}
            {% for band_member in object.members.all %}
                <tr class="table-light">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ band_member }}</td>
                    <td>
                        {% for membersection in membersection_list %}
                            {% if membersection.member == band_member %}
                                |{{ membersection.section }}{% if membersection.proficiency == 1 %} (L){% endif %}|
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'display:bandmember_delete' band.id band_member.id %}">Remove</a>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
{% endif %}

{% comment %}<a class="btn btn-primary" href="{% url 'display:bandmember_create' %}">Create Bandmember</a> {% endcomment %}


{% endblock %}

{% block footer %} {% endblock %}

super/templates/super/confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Deletion!</h1>

<p>Are you sure you want to delete this?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'super:home' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

super/templates/super/form.html
{% extends "base_bootstrap.html" %}

{% block welcome %} 
    <h1>Create/Update</h1>
    <h3>{{ object }}</h3>
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% load crispy_forms_tags %}
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'super:home' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

super/templates/super/super.html
{% extends "base_bootstrap.html" %}

{% block head %} {% endblock %}

{% block navbar %}{% include "nav.html" %}{% endblock %}

{% block welcome %} 

{% endblock %}

{% block content %}

<input type="submit" value="Back" onClick="javascript:history.go(-1);" class="btn btn-secondary">

<a class="btn btn-primary" href="{% url 'settings:admin' %}">Members' Event Contribution Page</a>

<h3 class="text-danger">Warning! Do not delete past events! This is to ensure proper history taking!</h3>

{% if object_list %}
    <table class="table table-hover table-bordered border-primary table-sm caption-top">
        <caption><a class="btn btn-success" href="{% url 'display:event_create' %}">Create Event</a></caption>
        <thead>
        <tr class="table-dark">
            <th scope="col">#</th>
            <th scope="col">Events</th>
            <th scope="col">Date & Time</th>
            <th scope="col">Bands</th>
            <th scope="col">Edit</th>
        </tr>
    </thead>
    <tbody>
    {% for event in object_list %}
        <tr class="{% if dateNow > event.date %}table-danger{% else %}table-success{% endif %}">
            {% comment %} Row Counter {% endcomment %}
            <th scope="row">{{ forloop.counter }}</th>

            {% comment %} Event Name {% endcomment %}
            <td>
                {{ event.name }}
                {% if dateNow > event.date %}
                    [ENDED]
                {% endif %}
            </td>

            {% comment %} Date | Time {% endcomment %}
            <td>{{ event.date }} | {{ event.time }}</td>

            {% comment %} Bands {% endcomment %}
            <td>
                <a class="btn btn-success" href="{% url 'display:band_create' event.id %}">Create</a>
                {% for band in event.bands.all %}
                <a class="btn btn-primary" href="{% url 'super:detail' band.id %}">{{ band }}</a>
                {% endfor %}
            </td>

            {% comment %} Event Editor {% endcomment %}
            <td>
                <a class="btn btn-success" href="{% url 'display:event_update' event.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'display:event_delete' event.id %}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endif %}

<a class="btn btn-primary" href="{% url 'admin:index' %}">Admin Page</a>

{% endblock %}

{% block footer %} {% endblock %}